[package]
name = "minimum_ops_equal_array"
version = "0.1.0"
authors = ["hilldrupca <hilldrupca@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
