import re

class Solution:
    def countAndSay(self, n: int) -> str:
        '''
        Generate the nth term of the count-and-say sequence, given 1 <= n <= 30.
        The count-and-say sequence starts with the following:
        
        1.  1
        2.  11
        3.  21
        4.  1211
        5.  111221
        
        The nth term is generated by counting aloud the numbers of the n-1 term.
        n=2 read n=1 as 'one 1' or 11, n=3 reads n=2 as "two 1s' or 21.
        
        Params:
            n - The count-and-say iteration of interest.
            
        Returns:
            str - The integers of the nth count-and-say sequence as a string.
            
        Examples:
            countAndSay(1)   ->   '1'
            
            countAndSay(4)   ->   '1211'
        '''
        res = '1'
        
        for x in range(1, n):
            nums = re.findall('0+|1+|2+|3+|4+|5+|6+|7+|8+|9+', res)
            temp = []
            for num in nums:
                temp.append(f'{len(num)}')
                temp.append(num[0])
        
            res = ''.join(temp)
            
        return res
